import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Thai } from "next/font/google";
import Script from "next/script";
import { Navbar } from "@/components/navbar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const notoSansThai = Noto_Sans_Thai({
  variable: "--font-noto-sans-thai",
  subsets: ["thai"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "rynne's site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${notoSansThai.variable} dark h-full antialiased`}
      style={{ colorScheme: "dark" }}
      suppressHydrationWarning
    >
      <head>
        <Script
          defer
          src="https://maplenan.org/hub/p.js"
          data-site="prt_jjudtdtrznlr4buly6yo"
          data-api="https://maplenan.org/hub/e"
        />
      </head>
      <body className="min-h-full flex flex-col font-sans relative bg-black">
        <div className="min-h-full flex flex-col">
          <ThemeProvider attribute="class" defaultTheme="dark">
            {/* Pink gradient fade at top */}
            <div className="pointer-events-none absolute inset-x-0 top-0 h-[300px] sm:h-[600px] bg-gradient-to-b from-[#f37cb37d] to-[#000000] -z-10" aria-hidden="true" />
            <Navbar />
            <main className="flex-1">{children}</main>
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
